import "@/styles/globals.css";

import Sidebar from "./_components/sidebar";
import Navbar from "./_components/navbar";

export const metadata = {
  title: "Dashboard",
  description: "Generated by Next.js",
};

export default function Dashboard({ children }: { children: React.ReactNode }) {
  return (
    <div>
      <div>
        <nav className="fixed left-0 top-0 h-[80px] w-full">
          <Navbar />
        </nav>
        <aside className="fixed top-[80px] hidden h-full shrink-0 md:flex md:w-56">
          <Sidebar />
        </aside>
        <main className="h-full pt-[80px] md:pl-56">{children}</main>
      </div>
    </div>
  );
}
