import "@/styles/globals.css";
import AppProvider from "@/providers/app-provider";

import { Inter } from "next/font/google";
import clsx from "clsx";
import Sidebar from "@/ui/sidebar";
import TopBar from "@/ui/top-bar";

// If loading a variable font, you don't need to specify the font weight
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Npm Trends",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={clsx(inter.className, " w-full")}>
        <div className="mx-auto max-w-7xl">
          <TopBar />
          <div className="grid lg:grid-cols-[300px_minmax(0,1fr)]">
            <Sidebar />

            <div>{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
